{{- if .Values.groups }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-groups-join
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}"
    release: "{{ template "releaseName" . }}"
    heritage: "{{ .Release.Service }}"
    job: {{ template "fullname" . }}-groups-join
    component: {{ .Chart.Name }}-groups-join
    dependency-level: "3"
  annotations:
    version: "{{ .Chart.Version }}"
spec:
  backoffLimit: 1
  template:
    metadata:
      name: "{{ template "releaseName" . }}"
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}"
        release: "{{ template "releaseName" . }}"
        heritage: "{{ .Release.Service }}"
        job: {{ template "fullname" . }}-groups-join
        component: {{ .Chart.Name }}-groups-join
        dependency-level: "3"
      annotations:
        version: "{{ .Chart.Version }}"
    spec:
      hostNetwork: {{ template "hostNetwork" . }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if index .Values "wait_for_groups" "enabled" }}
      initContainers:
        - name: wait-for-groups
          image: {{ .Values.wait_for.image }}
          imagePullPolicy: {{ template "imagePullPolicy" dict "root" . "context" .Values.wait_for }}
          args:
            - "job"
            - >
              -l release in ({{ template "releaseName" . }}), chart in ({{ .Chart.Name }}), dependency-level notin (0,1,2,3)
      {{- end }}
{{ include "imagePullSecrets" . | indent 6 }}
      restartPolicy: Never
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ template "imagePullPolicy" dict "root" . }}
        env:
          - name: ONEZONE_HOST
            value: "https://{{ template "onezone_name" . }}"
          - name: ONEPANEL_BASIC_AUTH
            value: "{{ template "onepanel_emergency_username_template" . }}:{{ template "onepanel_emergency_password_template" . }}"
          - name: ONEPROVIDER_HOST
            value: "https://{{ template "oneprovider_name" . }}"
          - name: ONEPANEL_HOST
            value: "https://{{ template "onezone_name" . }}:9443"
          - name: KEYCLOAK_HOST
            value: "http://{{ template "keycloak_service_url" . }}"
          - name: TERM # otherwise zsh and bash autocompletion used in this container tends to go crazy
            value: "xterm-256color"
        command:
          - "bash"
          - "-c"
          - >
            set -e ;
            echo "-k" > ~/.curlrc ; echo "-f" >> ~/.curlrc ;
            echo "Curl output:" ;
            echo "ONEZONE_HOST=$ONEZONE_HOST" ;
            echo "ONEPANEL_BASIC_AUTH=$ONEPANEL_BASIC_AUTH" ;
          {{- range .Values.users }}{{ if (hasKey . "idps"  )}}{{ if (hasKey .idps "keycloak" )}}{{ if and .idps.keycloak.enabled .idps.keycloak.onezoneLogin }}
            idp=keycloak-{{ template "onedata-chart-utils.keycloak_idpName_template" $ }};
            echo "Loging keycloak user={{ .name }} with password={{ .password }} to Onezone. User info from Onezone is: " ;
            TOKEN="$(curl -k --silent -u {{ .name }}:{{ .password }} http://{{ template "token-dispenser_name" $ }}/api/v1.0/token/$idp)" ;
            echo "Onezone api access TOKEN=$TOKEN" ;
            ONEZONE_API_KEY=$TOKEN onezone-rest-cli getCurrentUser ;
          {{- end }}{{ end }}{{ end }}{{ end }}
          {{- range $user := .Values.users }}
            {{- if (hasKey $user.idps "onepanel")}}{{ if ($user.idps.onepanel.enabled) }}
            idp=onepanel;
            {{- end }}{{ end }}
            {{- if (hasKey $user.idps "keycloak")}}{{ if ($user.idps.keycloak.enabled) }}
            idp=keycloak-{{ template "onedata-chart-utils.keycloak_idpName_template" $ }};
            {{- end -}}{{- end -}}
            echo "Getting userId for user={{ $user.name }} with password={{ $user.password }}" ;
            userId=$(curl --silent -k -u {{ $user.name }}:{{ $user.password }} http://{{ template "token-dispenser_name" $ }}/api/v2.0/onezone/uid/$idp) ;
            {{- $parent := . -}}
            {{- range .groups }}
            echo "Getting groupId for group={{ .group.name }} using user={{ template "admin_username_template" $ }} with password={{ template "admin_password_template" $ }}" ;
            groupId=$(onezone-rest-cli -u {{ template "admin_username_template" $ }}:{{ template "admin_password_template" $ }} getGroup | jq -r '.groups[]' | while read -r group_id ; do onezone-rest-cli -u {{ template "admin_username_template" $ }}:{{ template "admin_password_template" $ }} getGroup id=$group_id ; done | jq -r 'select(.name=="{{ .group.name }}").groupId') ;
            printf "Adding user {{ $parent.name }}($userId) to group {{ .group.name }}($groupId). [response: " ;
            onezone-rest-cli -u {{ template "admin_username_template" $ }}:{{ template "admin_password_template" $ }} -w "'%{http_code}'" {{ template "json_quoted_list" dict "name" "privileges" "list" .privileges -}} -H "'Content-type: application/json'" addGroupUser id=$groupId uid=$userId ;
            echo "]. Success added user {{ $parent.name }}($userId) to group {{ .group.name }}($groupId) with privileges(empty means default): {{ template "json_quoted_list" dict "name" "privileges" "list" .privileges -}}" ;
            {{- end }}
          {{- end }}
          {{- range .Values.groups_graph }}
            parent_group_id=$(onezone-rest-cli -u {{ template "admin_username_template" $ }}:{{ template "admin_password_template" $ }} getGroup | jq -r '.groups[]' | while read -r a_group_id ; do onezone-rest-cli -u {{ template "admin_username_template" $ }}:{{ template "admin_password_template" $ }} getGroup id=$a_group_id ; done | jq -r 'select(.name=="{{ .parent.name }}").groupId') ;
            {{- $parent := . -}}
            {{- range .children }}
            child_group_id=$(onezone-rest-cli -u {{ template "admin_username_template" $ }}:{{ template "admin_password_template" $ }} getGroup | jq -r '.groups[]' | while read -r a_group_id ; do onezone-rest-cli -u {{ template "admin_username_template" $ }}:{{ template "admin_password_template" $ }} getGroup id=$a_group_id ; done | jq -r 'select(.name=="{{ .name }}").groupId') ;
            printf "Admin user={{ template "admin_username_template" $ }} joining child group {{ .name }}($child_group_id) to parent group {{ $parent.parent.name }}($parent_group_id) with privileges(empty means default): {{ template "json_quoted_list" dict "name" "privileges" "list" $parent.privileges -}}. [response: " ;
            onezone-rest-cli -u {{ template "admin_username_template" $ }}:{{ template "admin_password_template" $ }} -w "'%{http_code}'" -u {{ template "admin_username_template" $ }}:{{ template "admin_password_template" $ }} {{ template "json_quoted_list" dict "name" "privileges" "list" $parent.privileges -}} -H "'Content-type: application/json'" addChildGroup id=$parent_group_id cid=$child_group_id ;
            echo "]. Success." ;
            {{- end }}
          {{- end }}
{{- end }}
