apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "fullname" . }}-pv
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ template "releaseName" . }}
    heritage: {{ .Release.Service }}
    component: {{ .Chart.Name }}
    type: nfs
    {{- if .Values.suffix }} 
    owner: {{ .Values.suffix }}
    {{- end }}
  annotations:
  {{- if .Values.deployAsPreInstallHook }}
    "helm.sh/hook": pre-install
  {{- end }}
    version: "{{ .Chart.Version }}"
spec:
  capacity:
    storage: {{ .Values.storage | quote }}
  accessModes:
    - ReadWriteMany
  # The NFS server pod is deleted anyway so no need to recycle
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolumeReclaimPolicy }}
  {{- if .Values.mount_options }}
  mountOptions:
{{ toYaml .Values.mount_options | indent 4 }}
  {{- end }}
  nfs:
    # TODO: The NFS server name is resolved using nodes resolve.conf
    # here we expect that nodes resovle.conf can resolve namespaces service name
    # to FQDN k8s domain. But this is a special case, usually NFS servers are not
    # deployed ad-hoc :)
    server: "{{ template "fullname" . }}.{{ .Release.Namespace }}"
    path: "/exports"