dependencies:
- name: onedata-chart-utils
  version: 0.2.11
  repository: file://../onedata-chart-utils

- name: onedata-3p
  version: 0.2.13
  repository: file://../onedata-3p
  condition: onedata-3p.enabled  
  import-values:
    - child: onezone.onezone_main_admin
      parent: global.onezoneMainAdmin
    - child: onezone.keycloak
      parent: global.keycloakInstance