dependencies:
- name: onezone
  version: 0.2.8
  repository: https://onedata.github.io/charts/

- name: oneprovider
  alias: oneprovider-krakow
  version: 0.2.9
  repository: https://onedata.github.io/charts/